GET http://localhost:3333/clients

###

POST http://localhost:3333/clients
Content-Type: application/json

{   
"name": "Siclano", 
"email":"siclano@mmail.com", 
"password":"123456", 
"cell":"139876321", 
"img_url":"my-photo"
}

###

POST http://localhost:3333/client/:name
Content-Type: application/json

{  
"name": "Beltrano",    
"password": "123456" 
}

