//Request client.js

GET http://localhost:3333/clients
Content-Type: application/json


###

POST http://localhost:3333/register-client
Content-Type: application/json

{
"name": "Joao", 
"email": "joao@mail.com", 
"cell": "13988", 
"password": "123"
}

###

GET http://localhost:3333/edit-client/:id
Content-Type: application/json

{  
"id": "1"
}

###

PUT  http://localhost:3333/edit-client/:id
Content-Type: application/json

{  
"id": "1"
}

###

DELETE http://localhost:3333/edit-client/:id
Content-Type: application/json

{  
"id": "1"
}

###
