GET http://localhost:3333//edit-company/:id


###

POST http://localhost:3333/add-product
Content-Type: application/json

{
"name": "pizza", 
"description": "queijo", 
"price": "20", 
"img_url": "uio", 
"limit_time": "89"
}

###

POST http://localhost:3333/login
Content-Type: application/json

{  
"email": "siclano@mmail.com",    
"password": "123456" 
}

###

DELETE  http://localhost:3333/products/:id
Content-Type: application/json

{  
"id": "1"
}


